import type { GridPosition, LayoutConfig, ZoneInstance } from "./types";

/**
 * Home Island — the finished illustrated terrain. The walkable grid, zone
 * positions, spawn and dock are all conformed to the painted art
 * (tools/island-art/home-island.png). See tools/island-art/README.md for the
 * registration math: grid cell (gx,gy) projects to world pixels via iso.ts,
 * and the art sprite is pinned with the same ART_SCALE + world origin so the
 * invisible walk-grid lines up with the painted coastline.
 *
 * Generated by tools/island-art/gen-layout.mjs — do not hand-edit the LAND_ROWS
 * / OBSTACLE_ROWS tables.
 */

const GRID_W = 56;
const GRID_H = 44;

// Per-row inclusive x-ranges, expanded into cell lists below.
const expand = (rows: Array<[number, Array<[number, number]>]>): GridPosition[] => {
  const out: GridPosition[] = [];
  for (const [y, ranges] of rows) {
    for (const [x0, x1] of ranges) {
      for (let x = x0; x <= x1; x++) out.push({ x, y });
    }
  }
  return out;
};

// Land footprint, derived by sampling the painted island's opacity through the
// iso projection (tools/island-art/derive-grid.mjs).
const LAND_ROWS: Array<[number, Array<[number, number]>]> = [
  [2, [[34,34]]],
  [3, [[30,39]]],
  [4, [[26,39]]],
  [5, [[23,40]]],
  [6, [[19,41]]],
  [7, [[12,12], [15,41]]],
  [8, [[8,8], [10,42], [44,44]]],
  [9, [[6,44]]],
  [10, [[5,44]]],
  [11, [[4,45]]],
  [12, [[4,47]]],
  [13, [[4,46]]],
  [14, [[3,48]]],
  [15, [[3,47]]],
  [16, [[2,47]]],
  [17, [[2,47]]],
  [18, [[2,47], [49,49]]],
  [19, [[3,47], [49,50]]],
  [20, [[2,49]]],
  [21, [[2,50]]],
  [22, [[2,50]]],
  [23, [[2,51]]],
  [24, [[2,51]]],
  [25, [[2,51]]],
  [26, [[2,53]]],
  [27, [[2,51], [53,53]]],
  [28, [[2,51], [53,53]]],
  [29, [[3,51], [53,53]]],
  [30, [[3,51]]],
  [31, [[3,51]]],
  [32, [[4,52]]],
  [33, [[5,50]]],
  [34, [[11,49]]],
  [35, [[10,49]]],
  [36, [[11,48]]],
  [37, [[11,47]]],
  [38, [[11,46]]],
  [39, [[13,13], [15,15], [17,17], [20,33], [35,44], [46,46]]],
  [40, [[19,21], [25,32], [35,38], [40,41], [44,44]]],
  [41, [[25,25], [27,27], [30,30], [38,39], [41,41]]],
];

// Tree/rock masses to keep the avatar OUT of — derived from the art's painted
// foliage/boulders (classifier in tools/island-art). Only clusters of >= 3
// cells are blocked, so big tree masses and boulders are impassable while small
// scattered bushes/pebbles stay walkable. Verified: spawn still connects to all
// seven zones and the dock approach.
const OBSTACLE_ROWS: Array<[number, Array<[number, number]>]> = [
  [5, [[36,36]]],
  [6, [[26,26], [36,38]]],
  [7, [[25,26], [35,39]]],
  [8, [[22,26], [35,38]]],
  [9, [[6,12], [22,26], [29,30], [36,38]]],
  [10, [[5,5], [8,15], [23,26], [29,38], [41,41]]],
  [11, [[9,10], [15,16], [21,25], [30,33], [42,42]]],
  [12, [[6,10], [13,17], [20,21], [23,24], [43,44]]],
  [13, [[6,7], [11,11], [13,14], [22,22], [41,44]]],
  [14, [[7,8], [11,11], [14,15], [41,43]]],
  [15, [[4,7], [11,11], [13,14], [41,44]]],
  [16, [[7,7], [10,12], [14,14], [37,37], [40,42]]],
  [17, [[7,13], [36,44]]],
  [18, [[7,7], [9,11], [36,36], [38,38], [43,44]]],
  [19, [[10,11], [42,44]]],
  [20, [[36,37], [41,45]]],
  [21, [[36,37], [41,45]]],
  [22, [[11,11], [35,36], [38,38], [41,44]]],
  [23, [[10,11], [38,40]]],
  [24, [[10,12], [39,40]]],
  [25, [[10,12]]],
  [26, [[3,3], [7,7], [9,11], [25,25]]],
  [27, [[3,3], [7,7], [9,12], [25,26]]],
  [28, [[3,3], [7,10], [16,16], [18,18], [23,24]]],
  [29, [[4,8], [15,15], [17,18], [22,23], [45,46]]],
  [30, [[13,18], [22,22], [29,29], [41,42], [44,44]]],
  [31, [[14,20], [22,22], [24,24], [26,30], [37,38], [43,43]]],
  [32, [[14,19], [22,22], [25,30], [33,34], [39,43]]],
  [33, [[12,12], [15,16], [18,19], [22,22], [24,31], [33,33], [35,35], [39,43]]],
  [34, [[12,14], [16,16], [18,22], [25,33], [35,44]]],
  [35, [[13,19], [22,22], [24,27], [29,36], [38,43]]],
  [36, [[15,15], [22,25], [27,32], [34,34], [36,36], [38,41]]],
  [37, [[22,22], [25,27], [29,30], [35,35], [38,39]]],
  [38, [[24,24]]],
];

const landCells: GridPosition[] = expand(LAND_ROWS);

// Seven landmark zones, snapped onto open clearings in the illustration.
export const sampleZones: ZoneInstance[] = [
  { key: "lighthouse_point", displayName: "Lighthouse Point", skinName: "Beacon Point", gridPosition: { x: 30, y: 4 }, footprint: { w: 4, h: 4 }, unlocked: true },
  { key: "treehouse_hideaway", displayName: "Treehouse Hideaway", skinName: "Treetop Hideaway", gridPosition: { x: 4, y: 20 }, footprint: { w: 5, h: 5 }, unlocked: true },
  { key: "art_hut", displayName: "Art Hut", skinName: "Paint Cabin", gridPosition: { x: 28, y: 20 }, footprint: { w: 4, h: 4 }, unlocked: true },
  { key: "campfire_circle", displayName: "Campfire Circle", skinName: "Marshmallow Ring", gridPosition: { x: 15, y: 21 }, footprint: { w: 4, h: 4 }, unlocked: true },
  { key: "arcade_cove", displayName: "Arcade Cove", skinName: "Arcade Cove", gridPosition: { x: 42, y: 24 }, footprint: { w: 5, h: 4 }, unlocked: true },
  { key: "calm_beach", displayName: "Calm Beach", skinName: "Calm Beach", gridPosition: { x: 5, y: 31 }, footprint: { w: 6, h: 4 }, unlocked: true },
  { key: "welcome_dock", displayName: "Welcome Dock", skinName: "Welcome Dock", gridPosition: { x: 43, y: 37 }, footprint: { w: 6, h: 4 }, unlocked: true },
];

// Spawn just inland (up-screen) of the welcome dock — the arrival sequence
// drops the avatar here after the boat pulls up.
const spawnPoint: GridPosition = { x: 44, y: 33 };

// Obstacle set = the painted tree/rock masses, with their frayed edges shaved.
// The classifier dilates each mass slightly, leaving thin 1-cell tendrils that
// poke into clearings and make the avatar detour around invisible padding. We
// drop any obstacle cell with >= 3 walkable orthogonal neighbours: such a cell
// is a protrusion spike (obstacle on at most one orthogonal side), so removing
// it tightens the boundary to the painted foliage without ever exposing a mass
// interior. The single pass is evaluated against the raw set so it cannot
// cascade inward and erode a mass body — big clusters stay fully blocked, and
// the avatar never appears to walk over a painted boulder, tree, or structure.
const obstacleCells: GridPosition[] = (() => {
  const raw = expand(OBSTACLE_ROWS);
  const landSet = new Set(landCells.map((c) => `${c.x},${c.y}`));
  const rawSet = new Set(raw.map((c) => `${c.x},${c.y}`));
  const zoneSet = new Set<string>();
  for (const z of sampleZones) {
    for (let dx = 0; dx < z.footprint.w; dx++) {
      for (let dy = 0; dy < z.footprint.h; dy++) {
        zoneSet.add(`${z.gridPosition.x + dx},${z.gridPosition.y + dy}`);
      }
    }
  }
  const isOpen = (x: number, y: number) =>
    landSet.has(`${x},${y}`) && !rawSet.has(`${x},${y}`) && !zoneSet.has(`${x},${y}`);
  const shaved = raw.filter((c) => {
    let open = 0;
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]] as const) {
      if (isOpen(c.x + dx, c.y + dy)) open++;
    }
    return open < 3; // keep mass bodies/edges; shave the frayed protrusion tips
  });
  // Shaving a tendril can leave a lone cell behind; drop tiny (<= 2 cell)
  // components so no isolated block sits in a clearing. Real masses are far
  // larger and are untouched.
  const shavedSet = new Set(shaved.map((c) => `${c.x},${c.y}`));
  const seen = new Set<string>();
  const N8 = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1], [-1, 1], [-1, -1]] as const;
  const keep: GridPosition[] = [];
  for (const c of shaved) {
    const k0 = `${c.x},${c.y}`;
    if (seen.has(k0)) continue;
    const comp: GridPosition[] = [];
    const stack = [c];
    seen.add(k0);
    while (stack.length) {
      const p = stack.pop()!;
      comp.push(p);
      for (const [dx, dy] of N8) {
        const k = `${p.x + dx},${p.y + dy}`;
        if (shavedSet.has(k) && !seen.has(k)) {
          seen.add(k);
          stack.push({ x: p.x + dx, y: p.y + dy });
        }
      }
    }
    if (comp.length > 2) keep.push(...comp);
  }
  return keep;
})();

export const sampleLayout: LayoutConfig = {
  grid: { w: GRID_W, h: GRID_H },
  landCells,
  obstacleCells,
  spawnPoint,
  // Reserved invisible anchor (future picture-frame video dock).
  pictureFrameAnchor: { x: 27, y: 23 },
  // The illustration is the scenery — no procedural decoration scatter.
  decorations: [],
  // Illustrated ground sprite, pinned to the grid via the registration math.
  terrainImage: {
    url: new URL("./assets/home-island.png", import.meta.url).href,
    originX: -1056,
    originY: 112,
    scale: 1.5,
  },
};
