import { Container, Sprite, Texture } from "pixi.js";

/**
 * LayeredIsland — the world map composed from individual illustrated sprites
 * instead of one flat painting. Pure presentation: it owns no world data and
 * never reads input. Build it with the textures, then call `layout()` with the
 * island's world-space bounds (and the landmark marks); it sizes + scatters
 * every layer to fit and keeps vegetation off the landmark sprites.
 *
 * Layer stack (bottom → top): water · sand · grass · rocks · flowers+bushes ·
 * trees. Landmarks and avatars are drawn ABOVE this container by the renderer,
 * so a landmark is always visible on top of the surrounding nature.
 *
 * The scatter is fully deterministic (seeded PRNG) so the island looks the
 * same on every load and every build.
 */
export interface IslandTextures {
  water: Texture;
  sand: Texture;
  grass: Texture;
  rock: Texture;
  tree01: Texture;
  tree02: Texture;
  bush01: Texture;
  bush02: Texture;
  flower01: Texture;
  flowerBush01: Texture;
}

/**
 * A landmark's world-space footprint, handed in so the vegetation scatter can
 * (a) ring grassy structures with green so they feel planted, (b) keep small
 * sandy clearings at the beach/dock/campfire, and (c) push trees off the
 * building sprites so they frame rather than cover them.
 */
export interface LandmarkMark {
  /** Zone key (so the flower scatter can target specific landmarks). */
  key: string;
  /** World-pixel centre x of the footprint. */
  x: number;
  /** World-pixel base/centre y of the footprint. */
  y: number;
  /** Footprint width in grid tiles (sizes the keep-out + grass ring). */
  w: number;
  /**
   * "grass" structures get a green ring + base tufts; "sand" structures
   * (campfire, welcome dock, calm beach) stay on bare sand and act as a grass
   * exclusion clearing.
   */
  ground: "grass" | "sand";
}

export interface IslandLayoutOpts {
  /**
   * Sand/island footprint, pinned to the painted-ground registration so the
   * (unchanged) landmarks sit on the sand. The sand is centered at (cx, cy)
   * and scaled so its width equals `spanW`.
   */
  cx: number;
  cy: number;
  spanW: number;
  /** World rect (centered on cx, cy) the water must blanket edge-to-edge —
   *  sized to the viewport at the most-zoomed-out level so there are no gaps. */
  waterW: number;
  waterH: number;
  /** Landmark footprints in world space (for grass rings + tree keep-out). */
  landmarks?: readonly LandmarkMark[];
}

/**
 * Baked tree positions, as offsets normalised to the sand half-extents
 * (x = cx + nx·shx, y = cy + ny·shy). Generated by sampling the sand-base alpha
 * so every trunk base lands on sand (≥~14px inside the waterline), avoiding the
 * landmark clearings — a mix of interior and pulled-in edge trees.
 */
const TREE_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0.101, -0.854], [0.572, -0.642], [0.055, -0.323], [0.673, -0.309],
  [0.324, -0.229], [-0.839, -0.189], [0.857, 0.069], [0.732, 0.270],
  [0.257, 0.290], [-0.441, 0.318], [0.039, 0.448], [-0.188, 0.509],
  [0.449, 0.537], [0.120, 0.730], [-0.296, 0.807],
];

// A tight forest cluster of smaller trees around the Treehouse Hideaway zone.
const CLUSTER_TREE_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [-0.476, -0.753], [-0.602, -0.595], [-0.228, -0.545], [-0.157, -0.419],
  [-0.303, -0.256],
];

// Illustrated bushes (bush-01 / bush-02), clustered near the treehouse forest
// and scattered along landmark edges. Sand-relative offsets, pre-sampled so
// each bush base sits on sand.
const BUSH_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [-0.269, -0.607], [-0.126, -0.593], [-0.571, -0.461], [0.248, -0.457],
  [-0.243, -0.404], [-0.076, -0.133], [0.331, 0.060], [-0.758, 0.096],
  [0.527, 0.887],
];

/** Small deterministic PRNG (mulberry32) — same seed ⇒ same island. */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class LayeredIsland {
  readonly container = new Container();

  private readonly water: Sprite;
  private readonly sand: Sprite;
  private readonly grass = new Container();
  private readonly rocks = new Container();
  private readonly flowers = new Container();
  private readonly bushes = new Container();
  private readonly trees = new Container();

  constructor(private readonly tex: IslandTextures) {
    this.water = new Sprite(tex.water);
    this.sand = new Sprite(tex.sand);
    this.water.anchor.set(0.5);
    this.sand.anchor.set(0.5);

    // Bottom → top: water · sand · grass · rocks · flowers+bushes · trees.
    // Landmarks/avatars draw above this whole container (in the renderer's
    // `entities`), so structures always sit on top of the nature.
    this.container.addChild(
      this.water, this.sand, this.grass, this.rocks, this.flowers, this.bushes, this.trees,
    );
    for (const c of [this.container, this.water, this.sand, this.grass,
      this.rocks, this.flowers, this.bushes, this.trees]) {
      c.eventMode = "none";
    }
    this.trees.sortableChildren = true;
    this.rocks.sortableChildren = true;
    this.grass.sortableChildren = true;
    this.bushes.sortableChildren = true;
    this.flowers.sortableChildren = true;
  }

  /**
   * Size + place every layer. The sand is pinned to the painted-ground
   * registration (cx/cy/spanW) so the landmarks line up; the water blankets the
   * requested rect; the props scatter over the sand. Idempotent and
   * deterministic, so it is safe to re-run on rebuild/resize.
   */
  layout(o: IslandLayoutOpts): void {
    // SAND — pinned to match the old painting's footprint exactly.
    const sandW = o.spanW;
    const sandScale = sandW / this.tex.sand.width;
    const sandH = this.tex.sand.height * sandScale;
    this.sand.scale.set(sandScale);
    this.sand.position.set(o.cx, o.cy);

    // WATER — blanket the requested rect edge-to-edge (no gaps at any zoom).
    this.coverWater(o.cx, o.cy, o.waterW, o.waterH);

    // Half-extents of the sand ellipse used for scatter placement.
    const shx = sandW / 2;
    const shy = sandH / 2;
    const marks = o.landmarks ?? [];

    const rockUnit = (sandH * 0.14) / this.tex.rock.height;

    this.scatterGrass(o.cx, o.cy, shx, shy, marks);
    this.scatterRocks(o.cx, o.cy, shx, shy, rockUnit);
    this.scatterFlowers(o.cx, o.cy, shx, shy, marks);
    this.scatterBushes(o.cx, o.cy, shx, shy);
    this.scatterTrees(o.cx, o.cy, shx, shy, marks);
  }

  /**
   * Heavy, lush grass coverage (grass-01). Three passes:
   *  • a green ring + base tufts around every grassy landmark so structures
   *    feel rooted in the landscape (not floating on bare sand);
   *  • an inner-edge band just inside the treeline;
   *  • interior fill between the landmarks.
   * Small sandy clearings are preserved around the campfire, welcome dock and
   * calm beach (the "sand" landmarks), which double as grass exclusion zones.
   */
  private scatterGrass(
    cx: number, cy: number, shx: number, shy: number, marks: readonly LandmarkMark[],
  ): void {
    this.grass.removeChildren();
    const r = rng(0x6a55);
    const clearings = marks.filter((m) => m.ground === "sand");
    const inClearing = (x: number, y: number): boolean =>
      clearings.some((m) => {
        const rad = 56 + m.w * 11; // keep the dock approach / beach / fire bare
        return Math.hypot(x - m.x, y - m.y) < rad;
      });

    // A green patch = a few tufts jittered around a point, so the grass reads as
    // a leafy clearing rather than a lone dot.
    const patch = (x: number, y: number, n: number, lo: number, hi: number): void => {
      for (let k = 0; k < n; k++) {
        const jx = x + (r() - 0.5) * 46;
        const jy = y + (r() - 0.5) * 22;
        this.stamp(this.grass, this.tex.grass, jx, jy, lo + r() * (hi - lo), (r() - 0.5) * 0.3);
      }
    };

    // Pass 1 — green clearings: a planted pad + ring patches at each grassy
    // landmark so the structure feels rooted in the landscape.
    for (const m of marks) {
      if (m.ground !== "grass") continue;
      const spread = 24 + m.w * 7;
      // Base pad: 4 small tufts tucked low around the structure's foot.
      for (let k = 0; k < 4; k++) {
        const a = (k / 4) * Math.PI * 2 + r() * 1.0;
        const x = m.x + Math.cos(a) * spread * (0.55 + r() * 0.5);
        const y = m.y + 8 + Math.abs(Math.sin(a)) * spread * 0.35;
        this.stamp(this.grass, this.tex.grass, x, y, 0.2 + r() * 0.15, (r() - 0.5) * 0.3);
      }
      // 3 larger clearing patches a little further out.
      for (let k = 0; k < 3; k++) {
        const a = r() * Math.PI * 2;
        const x = m.x + Math.cos(a) * spread * (1.3 + r() * 0.7);
        const y = m.y + 4 + Math.sin(a) * spread * 0.5;
        patch(x, y, 2, 0.38, 0.62);
      }
    }

    // Pass 2 — inner-edge band just inside the treeline.
    const EDGE = 16;
    for (let i = 0; i < EDGE; i++) {
      const a = (i / EDGE) * Math.PI * 2 + (r() - 0.5) * 0.5;
      const rad = 0.72 + r() * 0.16; // 0.72–0.88
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      if (inClearing(x, y)) continue;
      patch(x, y, 2, 0.32, 0.66);
    }

    // Pass 3 — interior fill between the landmarks (dense, clustered).
    const FILL = 18;
    for (let i = 0; i < FILL; i++) {
      const a = (i / FILL) * Math.PI * 2 + (r() - 0.5) * 0.9;
      const rad = 0.16 + r() * 0.56; // 0.16–0.72
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      if (inClearing(x, y)) continue;
      patch(x, y, 2 + (r() < 0.5 ? 1 : 0), 0.34, 0.7);
    }
  }

  // Rocks on the sand, some clustered near the edges.
  private scatterRocks(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.rocks.removeChildren();
    const r = rng(0x12c9);
    const N = 5;
    for (let i = 0; i < N; i++) {
      const a = (i / N) * Math.PI * 2 + (r() - 0.5) * 0.8;
      const rad = 0.55 + r() * 0.4;
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      const scale = (0.3 + r() * 0.3) * unit;
      this.stamp(this.rocks, this.tex.rock, x, y, scale);
    }
  }

  /**
   * Illustrated flower clusters (flower-01 / flower-bush-01), scale 0.25–0.5.
   * flower-01 hugs the water edges (calm beach, lazy lagoon, inner shore);
   * flower-bush-01 clusters by the treehouse, art hut and star market; a few
   * are scattered across the interior for discovery moments.
   */
  private scatterFlowers(
    cx: number, cy: number, shx: number, shy: number, marks: readonly LandmarkMark[],
  ): void {
    this.flowers.removeChildren();
    const r = rng(0xf10a);
    const at = (key: string) => marks.find((m) => m.key === key);

    const flower = (x: number, y: number, bush: boolean): void => {
      const tex = bush ? this.tex.flowerBush01 : this.tex.flower01;
      this.stamp(this.flowers, tex, x, y, 0.25 + r() * 0.25, (r() - 0.5) * 0.16);
    };
    const near = (m: LandmarkMark | undefined, n: number, bush: boolean, spread: number): void => {
      if (!m) return;
      for (let k = 0; k < n; k++) {
        const a = r() * Math.PI * 2;
        flower(m.x + Math.cos(a) * spread * (0.8 + r() * 0.7),
          m.y + 6 + Math.sin(a) * spread * 0.5, bush);
      }
    };

    // flower-01 near the water-edge landmarks.
    near(at("calm_beach"), 3, false, 64);
    near(at("lazy_lagoon"), 3, false, 60);
    // A few flower-01 along the inner south/west shore.
    for (let i = 0; i < 3; i++) {
      const a = Math.PI * (0.6 + i * 0.28) + (r() - 0.5) * 0.2; // SW arc
      const rad = 0.7 + r() * 0.16;
      flower(cx + Math.cos(a) * shx * rad, cy + Math.sin(a) * shy * rad, false);
    }

    // flower-bush-01 clustered by the leafier landmarks.
    near(at("treehouse_hideaway"), 2, true, 70);
    near(at("art_hut"), 2, true, 58);
    near(at("star_market"), 2, true, 56);

    // Interior discovery flowers (mix of both).
    const interior: ReadonlyArray<readonly [number, number, boolean]> = [
      [-0.05, 0.30, true], [0.30, -0.10, false], [-0.30, 0.05, false],
    ];
    for (const [nx, ny, bush] of interior) {
      flower(cx + nx * shx, cy + ny * shy, bush);
    }
  }

  // Illustrated bushes (bush-01 / bush-02), mix of both, scale 0.3–0.6.
  private scatterBushes(cx: number, cy: number, shx: number, shy: number): void {
    this.bushes.removeChildren();
    const r = rng(0xb05e);
    BUSH_OFFSETS.forEach(([nx, ny], i) => {
      const tex = i % 2 === 0 ? this.tex.bush01 : this.tex.bush02;
      const scale = 0.3 + r() * 0.3; // 0.3–0.6
      const rot = (r() - 0.5) * 0.16;
      this.stamp(this.bushes, tex, cx + nx * shx, cy + ny * shy, scale, rot);
    });
  }

  /**
   * Position + uniform-scale the water sprite so it blankets a world rect of
   * `w × h` centered on (cx, cy), with no gaps. Cheap; call on resize so the
   * ocean keeps filling the viewport at every zoom level.
   */
  coverWater(cx: number, cy: number, w: number, h: number): void {
    const s = Math.max(w / this.tex.water.width, h / this.tex.water.height);
    this.water.scale.set(s);
    this.water.position.set(cx, cy);
  }

  /** A sprite anchored at its base (so it "stands" on its placement point). */
  private stamp(layer: Container, tex: Texture, x: number, y: number, scale: number, rot = 0): void {
    const s = new Sprite(tex);
    s.anchor.set(0.5, 1);
    s.position.set(x, y);
    s.scale.set(scale);
    s.rotation = rot;
    s.eventMode = "none";
    s.zIndex = y; // y-sort: lower on screen draws in front
    layer.addChild(s);
  }

  // Trees. Positions are baked (offsets normalised to the sand half-extents)
  // and were pre-checked against the sand alpha so every trunk base sits on
  // sand. Any tree that would fall on a landmark sprite is pushed sideways out
  // of that landmark's keep-out box so trees frame structures, never cover them.
  private scatterTrees(
    cx: number, cy: number, shx: number, shy: number, marks: readonly LandmarkMark[],
  ): void {
    this.trees.removeChildren();
    const r = rng(0x9e3d);
    const place = (nx: number, ny: number, tex: Texture, scale: number): void => {
      let x = cx + nx * shx;
      const y = cy + ny * shy;
      x = this.keepOff(x, y, marks);
      // Stay on the sand horizontally after any nudge.
      x = Math.max(cx - shx * 0.93, Math.min(cx + shx * 0.93, x));
      this.stamp(this.trees, tex, x, y, scale);
    };
    // Main trees: tree-01 (even) 0.35–0.45, tree-02 (odd) 0.28–0.38.
    TREE_OFFSETS.forEach(([nx, ny], i) => {
      const even = i % 2 === 0;
      place(nx, ny, even ? this.tex.tree01 : this.tex.tree02, even ? 0.35 + r() * 0.1 : 0.28 + r() * 0.1);
    });
    // Treehouse forest cluster: smaller trees, 0.25–0.32, pulled back off the
    // treehouse so the building stays clearly visible.
    CLUSTER_TREE_OFFSETS.forEach(([nx, ny], i) => {
      place(nx, ny, i % 2 === 0 ? this.tex.tree01 : this.tex.tree02, 0.25 + r() * 0.07);
    });
  }

  /**
   * If (x, y) falls inside any landmark's keep-out box, push it horizontally to
   * the nearer edge so the tree sits beside the structure, not over it. The box
   * is tall above the base (where the sprite art rises) and shallow below it.
   */
  private keepOff(x: number, y: number, marks: readonly LandmarkMark[]): number {
    for (let pass = 0; pass < 2; pass++) {
      for (const m of marks) {
        const hx = 78 + m.w * 9;
        const above = 175, below = 55;
        const inVert = y <= m.y ? m.y - y < above : y - m.y < below;
        const dx = x - m.x;
        if (inVert && Math.abs(dx) < hx) {
          const dir = dx === 0 ? 1 : Math.sign(dx);
          x = m.x + dir * hx;
        }
      }
    }
    return x;
  }
}
