import { Container, Graphics, Sprite, Texture } from "pixi.js";

/**
 * LayeredIsland — the world map composed from individual illustrated sprites
 * instead of one flat painting. Pure presentation: it owns no world data and
 * never reads input. Build it with the six textures, then call `layout()` with
 * the island's world-space bounds; it sizes + scatters every layer to fit.
 *
 * Layer stack (bottom → top): water · sand · grass tufts · rocks · trees.
 * Landmarks and avatars are drawn ABOVE this container by the renderer.
 *
 * The scatter is fully deterministic (seeded PRNG) so the island looks the
 * same on every load and every build. Phase 1 is static — no animation here.
 */
export interface IslandTextures {
  water: Texture;
  sand: Texture;
  grass: Texture;
  rock: Texture;
  tree01: Texture;
  tree02: Texture;
}

export interface IslandLayoutOpts {
  /**
   * Sand/island footprint, pinned to the painted-ground registration so the
   * (unchanged) landmarks sit on the sand. The sand is centered at (cx, cy)
   * and scaled so its width equals `spanW`.
   */
  cx: number;
  cy: number;
  spanW: number;
  /** World rect (centered on cx, cy) the water must blanket edge-to-edge —
   *  sized to the viewport at the most-zoomed-out level so there are no gaps. */
  waterW: number;
  waterH: number;
}

/**
 * Baked tree positions, as offsets normalised to the sand half-extents
 * (x = cx + nx·shx, y = cy + ny·shy). Generated by sampling the sand-base alpha
 * so every trunk base lands on sand (≥~14px inside the waterline), avoiding the
 * landmark clearings — a mix of interior and pulled-in edge trees. Sorted by y
 * for painter ordering.
 */
const TREE_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0.097, -0.854], [-0.214, -0.833], [-0.469, -0.803], [0.581, -0.634],
  [-0.188, -0.570], [-0.690, -0.526], [-0.198, -0.345], [-0.499, -0.331],
  [0.034, -0.323], [0.677, -0.299], [-0.832, -0.216], [0.228, -0.200],
  [0.462, -0.170], [0.858, -0.053], [0.192, 0.282], [0.775, 0.373],
  [-0.484, 0.448], [0.419, 0.658], [0.197, 0.755], [-0.214, 0.833],
];

/** Flower-cluster anchor points (sand-relative). Each renders 3–5 small warm
 *  blossoms. Generated against the sand alpha so they sit on sand. */
const FLOWER_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0.528, -0.472], [0.140, -0.393], [-0.399, -0.272], [-0.061, -0.248],
  [0.398, -0.214], [0.249, 0.229], [-0.358, 0.266], [0.116, 0.484],
  [-0.133, 0.617],
];

/** Bush anchor points (sand-relative), placed near trees/landmark edges. */
const BUSH_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [-0.329, -0.877], [-0.061, -0.780], [-0.489, -0.708], [-0.666, -0.633],
  [-0.711, -0.279], [0.102, 0.700], [0.356, 0.791],
];

/** Small deterministic PRNG (mulberry32) — same seed ⇒ same island. */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class LayeredIsland {
  readonly container = new Container();

  private readonly water: Sprite;
  private readonly sand: Sprite;
  private readonly grass = new Container();
  private readonly flowers = new Graphics();
  private readonly bushes = new Graphics();
  private readonly rocks = new Container();
  private readonly trees = new Container();

  constructor(private readonly tex: IslandTextures) {
    this.water = new Sprite(tex.water);
    this.sand = new Sprite(tex.sand);
    this.water.anchor.set(0.5);
    this.sand.anchor.set(0.5);

    // Bottom → top. Grass/rocks/trees are y-sorted internally; flowers (flat)
    // and bushes (low rounded greenery) sit between the grass and the props.
    this.container.addChild(
      this.water, this.sand, this.grass, this.flowers, this.bushes, this.rocks, this.trees,
    );
    for (const c of [this.container, this.water, this.sand, this.grass,
      this.flowers, this.bushes, this.rocks, this.trees]) {
      c.eventMode = "none";
    }
    this.trees.sortableChildren = true;
    this.rocks.sortableChildren = true;
    this.grass.sortableChildren = true;
  }

  /**
   * Size + place every layer. The sand is pinned to the painted-ground
   * registration (cx/cy/spanW) so the landmarks line up; the water blankets the
   * requested rect; the props scatter over the sand. Idempotent and
   * deterministic, so it is safe to re-run on rebuild/resize.
   */
  layout(o: IslandLayoutOpts): void {
    // SAND — pinned to match the old painting's footprint exactly.
    const sandW = o.spanW;
    const sandScale = sandW / this.tex.sand.width;
    const sandH = this.tex.sand.height * sandScale;
    this.sand.scale.set(sandScale);
    this.sand.position.set(o.cx, o.cy);

    // WATER — blanket the requested rect edge-to-edge (no gaps at any zoom).
    this.coverWater(o.cx, o.cy, o.waterW, o.waterH);

    // Half-extents of the sand ellipse used for scatter placement.
    const shx = sandW / 2;
    const shy = sandH / 2;

    // Prop sizes are a fraction of the SAND height, so the tree ring, grass and
    // rocks scale proportionally whenever the island is resized.
    const treeUnit = (sandH * 0.27) / this.tex.tree01.height;
    const grassUnit = (sandH * 0.11) / this.tex.grass.height;
    const rockUnit = (sandH * 0.14) / this.tex.rock.height;

    this.scatterGrass(o.cx, o.cy, shx, shy, grassUnit);
    this.drawFlowers(o.cx, o.cy, shx, shy, sandH);
    this.drawBushes(o.cx, o.cy, shx, shy, sandH);
    this.scatterRocks(o.cx, o.cy, shx, shy, rockUnit);
    this.scatterTrees(o.cx, o.cy, shx, shy, treeUnit);
  }

  // Small charming flower clusters (3–5 warm blossoms each), drawn flat on the
  // sand. Programmatic — no PNG assets.
  private drawFlowers(cx: number, cy: number, shx: number, shy: number, sandH: number): void {
    this.flowers.clear();
    const r = rng(0xf10a);
    const petalCols = [0xff9fb6, 0xffd36e, 0xfff3d6, 0xf6a5c0, 0xffe08a];
    const unit = sandH * 0.011; // blossom radius in world px
    for (const [nx, ny] of FLOWER_OFFSETS) {
      const bx = cx + nx * shx;
      const by = cy + ny * shy;
      const n = 3 + Math.floor(r() * 3); // 3–5 blossoms
      for (let i = 0; i < n; i++) {
        const fx = bx + (r() - 0.5) * unit * 7;
        const fy = by + (r() - 0.5) * unit * 4;
        const pr = unit * (0.8 + r() * 0.5);
        const col = petalCols[Math.floor(r() * petalCols.length)];
        // five petals + a yellow centre
        for (let p = 0; p < 5; p++) {
          const a = (p / 5) * Math.PI * 2 + r();
          this.flowers.circle(fx + Math.cos(a) * pr, fy + Math.sin(a) * pr * 0.7, pr * 0.7).fill(col);
        }
        this.flowers.circle(fx, fy, pr * 0.55).fill(0xfff0a6);
      }
    }
  }

  // Rounded bushes — a touch darker than the grass — near trees / landmark edges.
  private drawBushes(cx: number, cy: number, shx: number, shy: number, sandH: number): void {
    this.bushes.clear();
    const r = rng(0xb05e);
    const base = sandH * 0.05; // bush radius in world px
    for (const [nx, ny] of BUSH_OFFSETS) {
      const bx = cx + nx * shx;
      const by = cy + ny * shy;
      const s = base * (0.8 + r() * 0.5);
      // soft contact shadow
      this.bushes.ellipse(bx, by, s * 1.15, s * 0.34).fill({ color: 0x000000, alpha: 0.12 });
      // a few overlapping rounded lobes, bottom-anchored
      const lobes = 3 + Math.floor(r() * 2);
      for (let i = 0; i < lobes; i++) {
        const ox = (i - (lobes - 1) / 2) * s * 0.7 + (r() - 0.5) * s * 0.3;
        const oy = -s * (0.35 + r() * 0.2);
        this.bushes.circle(bx + ox, by + oy, s * (0.6 + r() * 0.25)).fill(0x6f9a3a);
      }
      // lighter top dabs
      this.bushes.circle(bx - s * 0.2, by - s * 0.7, s * 0.42).fill({ color: 0x8cb84f, alpha: 0.85 });
    }
  }

  /**
   * Position + uniform-scale the water sprite so it blankets a world rect of
   * `w × h` centered on (cx, cy), with no gaps. Cheap; call on resize so the
   * ocean keeps filling the viewport at every zoom level.
   */
  coverWater(cx: number, cy: number, w: number, h: number): void {
    const s = Math.max(w / this.tex.water.width, h / this.tex.water.height);
    this.water.scale.set(s);
    this.water.position.set(cx, cy);
  }

  /** A sprite anchored at its base (so it "stands" on its placement point). */
  private stamp(layer: Container, tex: Texture, x: number, y: number, scale: number, rot = 0): void {
    const s = new Sprite(tex);
    s.anchor.set(0.5, 1);
    s.position.set(x, y);
    s.scale.set(scale);
    s.rotation = rot;
    s.eventMode = "none";
    s.zIndex = y; // y-sort: lower on screen draws in front
    layer.addChild(s);
  }

  // Layer 3 — grass tufts toward the edges and between zones.
  private scatterGrass(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.grass.removeChildren();
    const r = rng(0x6a55);
    const N = 9;
    for (let i = 0; i < N; i++) {
      const a = (i / N) * Math.PI * 2 + (r() - 0.5) * 0.6;
      const rad = 0.5 + r() * 0.42; // bias outward
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      const scale = (0.4 + r() * 0.4) * unit;
      const rot = (r() - 0.5) * 0.2; // ±0.1 rad
      this.stamp(this.grass, this.tex.grass, x, y, scale, rot);
    }
  }

  // Layer 4 — rocks on the sand, some clustered near the edges.
  private scatterRocks(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.rocks.removeChildren();
    const r = rng(0x12c9);
    const N = 5;
    for (let i = 0; i < N; i++) {
      const a = (i / N) * Math.PI * 2 + (r() - 0.5) * 0.8;
      const rad = 0.55 + r() * 0.4;
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      const scale = (0.3 + r() * 0.3) * unit;
      this.stamp(this.rocks, this.tex.rock, x, y, scale);
    }
  }

  // Layer 5 — trees. Positions are baked (offsets normalised to the sand
  // half-extents) and were pre-checked against the sand alpha so every trunk
  // base sits on sand, not the waterline. A mix of interior + edge, pulled in
  // far enough to stay on the island. Alternating sprite, varied scale.
  private scatterTrees(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.trees.removeChildren();
    const r = rng(0x9e3d);
    TREE_OFFSETS.forEach(([nx, ny], i) => {
      const x = cx + nx * shx;
      const y = cy + ny * shy;
      const tex = i % 2 === 0 ? this.tex.tree01 : this.tex.tree02;
      const scale = (0.6 + r() * 0.4) * unit;
      this.stamp(this.trees, tex, x, y, scale);
    });
  }
}
