import { Container, Sprite, Texture } from "pixi.js";

/**
 * LayeredIsland — the world map composed from individual illustrated sprites
 * instead of one flat painting. Pure presentation: it owns no world data and
 * never reads input. Build it with the six textures, then call `layout()` with
 * the island's world-space bounds; it sizes + scatters every layer to fit.
 *
 * Layer stack (bottom → top): water · sand · grass tufts · rocks · trees.
 * Landmarks and avatars are drawn ABOVE this container by the renderer.
 *
 * The scatter is fully deterministic (seeded PRNG) so the island looks the
 * same on every load and every build. Phase 1 is static — no animation here.
 */
export interface IslandTextures {
  water: Texture;
  sand: Texture;
  grass: Texture;
  rock: Texture;
  tree01: Texture;
  tree02: Texture;
  bush01: Texture;
  bush02: Texture;
  flower01: Texture;
  flowerBush01: Texture;
}

export interface IslandLayoutOpts {
  /**
   * Sand/island footprint, pinned to the painted-ground registration so the
   * (unchanged) landmarks sit on the sand. The sand is centered at (cx, cy)
   * and scaled so its width equals `spanW`.
   */
  cx: number;
  cy: number;
  spanW: number;
  /** World rect (centered on cx, cy) the water must blanket edge-to-edge —
   *  sized to the viewport at the most-zoomed-out level so there are no gaps. */
  waterW: number;
  waterH: number;
}

/**
 * Baked tree positions, as offsets normalised to the sand half-extents
 * (x = cx + nx·shx, y = cy + ny·shy). Generated by sampling the sand-base alpha
 * so every trunk base lands on sand (≥~14px inside the waterline), avoiding the
 * landmark clearings — a mix of interior and pulled-in edge trees. Sorted by y
 * for painter ordering.
 */
// Main tree positions (sand-relative offsets), pre-sampled against the sand
// alpha so every trunk sits on sand, avoiding the landmark clearings.
const TREE_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0.101, -0.854], [0.572, -0.642], [0.055, -0.323], [0.673, -0.309],
  [0.324, -0.229], [-0.839, -0.189], [0.857, 0.069], [0.732, 0.270],
  [0.257, 0.290], [-0.441, 0.318], [0.039, 0.448], [-0.188, 0.509],
  [0.449, 0.537], [0.120, 0.730], [-0.296, 0.807],
];

// A tight forest cluster of smaller trees around the Treehouse Hideaway zone.
const CLUSTER_TREE_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [-0.476, -0.753], [-0.602, -0.595], [-0.228, -0.545], [-0.157, -0.419],
  [-0.303, -0.256],
];

// Illustrated flower clusters (flower-01 / flower-bush-01) — near Calm Beach,
// Star Market, and a few other landmarks.
const FLOWER_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0.148, -0.837], [-0.594, -0.197], [-0.172, -0.111], [-0.636, 0.182],
  [0.702, 0.204], [-0.514, 0.361], [-0.687, 0.673],
];

// Illustrated bushes (bush-01 / bush-02), clustered near the treehouse forest
// and scattered along landmark edges.
const BUSH_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [-0.269, -0.607], [-0.126, -0.593], [-0.571, -0.461], [0.248, -0.457],
  [-0.243, -0.404], [-0.076, -0.133], [0.331, 0.060], [-0.758, 0.096],
  [0.527, 0.887],
];

/** Small deterministic PRNG (mulberry32) — same seed ⇒ same island. */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class LayeredIsland {
  readonly container = new Container();

  private readonly water: Sprite;
  private readonly sand: Sprite;
  private readonly grass = new Container();
  private readonly flowers = new Container();
  private readonly bushes = new Container();
  private readonly rocks = new Container();
  private readonly trees = new Container();

  constructor(private readonly tex: IslandTextures) {
    this.water = new Sprite(tex.water);
    this.sand = new Sprite(tex.sand);
    this.water.anchor.set(0.5);
    this.sand.anchor.set(0.5);

    // Bottom → top. Grass/flowers sit low; bushes/rocks/trees are y-sorted
    // illustrated props above them.
    this.container.addChild(
      this.water, this.sand, this.grass, this.flowers, this.bushes, this.rocks, this.trees,
    );
    for (const c of [this.container, this.water, this.sand, this.grass,
      this.flowers, this.bushes, this.rocks, this.trees]) {
      c.eventMode = "none";
    }
    this.trees.sortableChildren = true;
    this.rocks.sortableChildren = true;
    this.grass.sortableChildren = true;
    this.bushes.sortableChildren = true;
    this.flowers.sortableChildren = true;
  }

  /**
   * Size + place every layer. The sand is pinned to the painted-ground
   * registration (cx/cy/spanW) so the landmarks line up; the water blankets the
   * requested rect; the props scatter over the sand. Idempotent and
   * deterministic, so it is safe to re-run on rebuild/resize.
   */
  layout(o: IslandLayoutOpts): void {
    // SAND — pinned to match the old painting's footprint exactly.
    const sandW = o.spanW;
    const sandScale = sandW / this.tex.sand.width;
    const sandH = this.tex.sand.height * sandScale;
    this.sand.scale.set(sandScale);
    this.sand.position.set(o.cx, o.cy);

    // WATER — blanket the requested rect edge-to-edge (no gaps at any zoom).
    this.coverWater(o.cx, o.cy, o.waterW, o.waterH);

    // Half-extents of the sand ellipse used for scatter placement.
    const shx = sandW / 2;
    const shy = sandH / 2;

    // Prop sizes are a fraction of the SAND height, so the tree ring, grass and
    // rocks scale proportionally whenever the island is resized.
    const grassUnit = (sandH * 0.11) / this.tex.grass.height;
    const rockUnit = (sandH * 0.14) / this.tex.rock.height;

    this.scatterGrass(o.cx, o.cy, shx, shy, grassUnit);
    this.scatterFlowers(o.cx, o.cy, shx, shy);
    this.scatterBushes(o.cx, o.cy, shx, shy);
    this.scatterRocks(o.cx, o.cy, shx, shy, rockUnit);
    this.scatterTrees(o.cx, o.cy, shx, shy);
  }

  // Illustrated flower clusters (flower-01 / flower-bush-01), scale 0.25–0.45.
  private scatterFlowers(cx: number, cy: number, shx: number, shy: number): void {
    this.flowers.removeChildren();
    const r = rng(0xf10a);
    FLOWER_OFFSETS.forEach(([nx, ny], i) => {
      const tex = i % 2 === 0 ? this.tex.flower01 : this.tex.flowerBush01;
      const scale = 0.25 + r() * 0.2; // 0.25–0.45
      const rot = (r() - 0.5) * 0.1;
      this.stamp(this.flowers, tex, cx + nx * shx, cy + ny * shy, scale, rot);
    });
  }

  // Illustrated bushes (bush-01 / bush-02), mix of both, scale 0.3–0.6.
  private scatterBushes(cx: number, cy: number, shx: number, shy: number): void {
    this.bushes.removeChildren();
    const r = rng(0xb05e);
    BUSH_OFFSETS.forEach(([nx, ny], i) => {
      const tex = i % 2 === 0 ? this.tex.bush01 : this.tex.bush02;
      const scale = 0.3 + r() * 0.3; // 0.3–0.6
      const rot = (r() - 0.5) * 0.16;
      this.stamp(this.bushes, tex, cx + nx * shx, cy + ny * shy, scale, rot);
    });
  }

  /**
   * Position + uniform-scale the water sprite so it blankets a world rect of
   * `w × h` centered on (cx, cy), with no gaps. Cheap; call on resize so the
   * ocean keeps filling the viewport at every zoom level.
   */
  coverWater(cx: number, cy: number, w: number, h: number): void {
    const s = Math.max(w / this.tex.water.width, h / this.tex.water.height);
    this.water.scale.set(s);
    this.water.position.set(cx, cy);
  }

  /** A sprite anchored at its base (so it "stands" on its placement point). */
  private stamp(layer: Container, tex: Texture, x: number, y: number, scale: number, rot = 0): void {
    const s = new Sprite(tex);
    s.anchor.set(0.5, 1);
    s.position.set(x, y);
    s.scale.set(scale);
    s.rotation = rot;
    s.eventMode = "none";
    s.zIndex = y; // y-sort: lower on screen draws in front
    layer.addChild(s);
  }

  // Layer 3 — grass tufts toward the edges and between zones.
  private scatterGrass(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.grass.removeChildren();
    const r = rng(0x6a55);
    const N = 9;
    for (let i = 0; i < N; i++) {
      const a = (i / N) * Math.PI * 2 + (r() - 0.5) * 0.6;
      const rad = 0.5 + r() * 0.42; // bias outward
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      const scale = (0.4 + r() * 0.4) * unit;
      const rot = (r() - 0.5) * 0.2; // ±0.1 rad
      this.stamp(this.grass, this.tex.grass, x, y, scale, rot);
    }
  }

  // Layer 4 — rocks on the sand, some clustered near the edges.
  private scatterRocks(cx: number, cy: number, shx: number, shy: number, unit: number): void {
    this.rocks.removeChildren();
    const r = rng(0x12c9);
    const N = 5;
    for (let i = 0; i < N; i++) {
      const a = (i / N) * Math.PI * 2 + (r() - 0.5) * 0.8;
      const rad = 0.55 + r() * 0.4;
      const x = cx + Math.cos(a) * shx * rad;
      const y = cy + Math.sin(a) * shy * rad;
      const scale = (0.3 + r() * 0.3) * unit;
      this.stamp(this.rocks, this.tex.rock, x, y, scale);
    }
  }

  // Layer 5 — trees. Positions are baked (offsets normalised to the sand
  // half-extents) and were pre-checked against the sand alpha so every trunk
  // base sits on sand, not the waterline. A mix of interior + edge, pulled in
  // far enough to stay on the island. Alternating sprite, varied scale.
  private scatterTrees(cx: number, cy: number, shx: number, shy: number): void {
    this.trees.removeChildren();
    const r = rng(0x9e3d);
    // Main trees: tree-01 (even) 0.35–0.45, tree-02 (odd) 0.28–0.38.
    TREE_OFFSETS.forEach(([nx, ny], i) => {
      const even = i % 2 === 0;
      const tex = even ? this.tex.tree01 : this.tex.tree02;
      const scale = even ? 0.35 + r() * 0.1 : 0.28 + r() * 0.1;
      this.stamp(this.trees, tex, cx + nx * shx, cy + ny * shy, scale);
    });
    // Treehouse forest cluster: smaller trees, 0.25–0.32.
    CLUSTER_TREE_OFFSETS.forEach(([nx, ny], i) => {
      const tex = i % 2 === 0 ? this.tex.tree01 : this.tex.tree02;
      const scale = 0.25 + r() * 0.07;
      this.stamp(this.trees, tex, cx + nx * shx, cy + ny * shy, scale);
    });
  }
}
