/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedStudioIslandRouteImport } from './routes/_authenticated/studio/island'
import { Route as AuthenticatedStudioActivitiesRouteImport } from './routes/_authenticated/studio/activities'
import { Route as AuthenticatedStudioResidentsIndexRouteImport } from './routes/_authenticated/studio/residents/index'
import { Route as AuthenticatedStudioResidentsNewRouteImport } from './routes/_authenticated/studio/residents/new'
import { Route as AuthenticatedStudioResidentsIdRouteImport } from './routes/_authenticated/studio/residents/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIslandRoute =
  AuthenticatedStudioIslandRouteImport.update({
    id: '/studio/island',
    path: '/studio/island',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioActivitiesRoute =
  AuthenticatedStudioActivitiesRouteImport.update({
    id: '/studio/activities',
    path: '/studio/activities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioResidentsIndexRoute =
  AuthenticatedStudioResidentsIndexRouteImport.update({
    id: '/studio/residents/',
    path: '/studio/residents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioResidentsNewRoute =
  AuthenticatedStudioResidentsNewRouteImport.update({
    id: '/studio/residents/new',
    path: '/studio/residents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioResidentsIdRoute =
  AuthenticatedStudioResidentsIdRouteImport.update({
    id: '/studio/residents/$id',
    path: '/studio/residents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio/activities': typeof AuthenticatedStudioActivitiesRoute
  '/studio/island': typeof AuthenticatedStudioIslandRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/studio/residents/$id': typeof AuthenticatedStudioResidentsIdRoute
  '/studio/residents/new': typeof AuthenticatedStudioResidentsNewRoute
  '/studio/residents/': typeof AuthenticatedStudioResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio/activities': typeof AuthenticatedStudioActivitiesRoute
  '/studio/island': typeof AuthenticatedStudioIslandRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/studio/residents/$id': typeof AuthenticatedStudioResidentsIdRoute
  '/studio/residents/new': typeof AuthenticatedStudioResidentsNewRoute
  '/studio/residents': typeof AuthenticatedStudioResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/studio/activities': typeof AuthenticatedStudioActivitiesRoute
  '/_authenticated/studio/island': typeof AuthenticatedStudioIslandRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/studio/residents/$id': typeof AuthenticatedStudioResidentsIdRoute
  '/_authenticated/studio/residents/new': typeof AuthenticatedStudioResidentsNewRoute
  '/_authenticated/studio/residents/': typeof AuthenticatedStudioResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/studio/activities'
    | '/studio/island'
    | '/admin/'
    | '/studio/'
    | '/studio/residents/$id'
    | '/studio/residents/new'
    | '/studio/residents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/studio/activities'
    | '/studio/island'
    | '/admin'
    | '/studio'
    | '/studio/residents/$id'
    | '/studio/residents/new'
    | '/studio/residents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/studio/activities'
    | '/_authenticated/studio/island'
    | '/_authenticated/admin/'
    | '/_authenticated/studio/'
    | '/_authenticated/studio/residents/$id'
    | '/_authenticated/studio/residents/new'
    | '/_authenticated/studio/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/island': {
      id: '/_authenticated/studio/island'
      path: '/studio/island'
      fullPath: '/studio/island'
      preLoaderRoute: typeof AuthenticatedStudioIslandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/activities': {
      id: '/_authenticated/studio/activities'
      path: '/studio/activities'
      fullPath: '/studio/activities'
      preLoaderRoute: typeof AuthenticatedStudioActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/residents/': {
      id: '/_authenticated/studio/residents/'
      path: '/studio/residents'
      fullPath: '/studio/residents/'
      preLoaderRoute: typeof AuthenticatedStudioResidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/residents/new': {
      id: '/_authenticated/studio/residents/new'
      path: '/studio/residents/new'
      fullPath: '/studio/residents/new'
      preLoaderRoute: typeof AuthenticatedStudioResidentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/residents/$id': {
      id: '/_authenticated/studio/residents/$id'
      path: '/studio/residents/$id'
      fullPath: '/studio/residents/$id'
      preLoaderRoute: typeof AuthenticatedStudioResidentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioActivitiesRoute: typeof AuthenticatedStudioActivitiesRoute
  AuthenticatedStudioIslandRoute: typeof AuthenticatedStudioIslandRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
  AuthenticatedStudioResidentsIdRoute: typeof AuthenticatedStudioResidentsIdRoute
  AuthenticatedStudioResidentsNewRoute: typeof AuthenticatedStudioResidentsNewRoute
  AuthenticatedStudioResidentsIndexRoute: typeof AuthenticatedStudioResidentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioActivitiesRoute: AuthenticatedStudioActivitiesRoute,
  AuthenticatedStudioIslandRoute: AuthenticatedStudioIslandRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
  AuthenticatedStudioResidentsIdRoute: AuthenticatedStudioResidentsIdRoute,
  AuthenticatedStudioResidentsNewRoute: AuthenticatedStudioResidentsNewRoute,
  AuthenticatedStudioResidentsIndexRoute:
    AuthenticatedStudioResidentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
